Resources:
  default:
    Type: TencentCloud::Serverless::Namespace
    hello_world:
      Type: TencentCloud::Serverless::Function
      Properties:
        CodeUri: ./smzdm-bot
        Type: Event
        Description: 什么值得买自动签到
        Environment:
          Variables:
            ENV_FIRST: env1
            ENV_SECOND: env2
        Handler: index.main_handler
        MemorySize: 64 # 配置配额，云函数的耗费会跟这个配置有关
        Runtime: Python3.6
        Timeout: 100
        #VpcConfig:
        #    VpcId: 'vpc-qdqc5k2p'
        #    SubnetId: 'subnet-pad6l61i'
        #Events:
        #    timer:
        #        Type: Timer
        #        Properties:
        #            CronExpression: '*/5 * * * *'
        #            Enable: True
        #    cli-appid.cos.ap-beijing.myqcloud.com: # full bucket name
        #        Type: COS
        #        Properties:
        #            Bucket: cli-appid.cos.ap-beijing.myqcloud.com
        #            Filter:
        #                Prefix: filterdir/
        #                Suffix: .jpg
        #            Events: cos:ObjectCreated:*
        #            Enable: True
        #    topic:            # topic name
        #        Type: CMQ
        #        Properties:
        #            Name: qname
        #    hello_world_apigw:  # ${FunctionName} + '_apigw'
        #        Type: APIGW
        #        Properties:
        #            StageName: release
        #            ServiceId:
        #            HttpMethod: ANY

Globals:
  Function:
    Timeout: 100
